sonar.organization=owlnext-fr
sonar.projectKey=owlnext-fr_latch
sonar.sources=frontend/src,Dockerfile,docker-compose.yml,.github
sonar.tests=frontend/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.exclusions=frontend/src/api/schema.d.ts,**/*.config.ts
sonar.qualitygate.wait=true
