/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/login — vérifie ADMIN_USER/ADMIN_PASS à temps constant, pose la session. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/logout — invalide la session côté serveur (supprime la ligne en DB). */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/projects — liste tous les projets (sans PIN, invariant §9.2). */
        get: operations["list"];
        put?: never;
        /** POST /api/projects — crée un nouveau projet. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/projects/{id} — détail d'un projet avec ses versions et son PIN. */
        get: operations["detail"];
        /** PUT /api/projects/{id} — met à jour le nom ou le brand_name d'un projet. */
        put: operations["update"];
        post?: never;
        /** DELETE /api/projects/{id} — supprime un projet et ses versions. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/projects/{id}/code — active le code d'accès avec le PIN fourni. */
        post: operations["set_code"];
        /** DELETE /api/projects/{id}/code — désactive le code d'accès (PIN effacé). */
        delete: operations["clear_code"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/comments/messages/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** DELETE /api/projects/{id}/comments/messages/{cid} — modération (vérifie l'appartenance au projet). */
        delete: operations["moderate_delete_comment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/projects/{id}/deploy — déploie un nouveau HTML, crée une version. */
        post: operations["deploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/versions/{n}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** DELETE /api/projects/{id}/versions/{n} — supprime une version NON active. */
        delete: operations["delete_version"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/versions/{n}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/projects/{id}/versions/{n}/activate — bascule le pointeur actif. */
        post: operations["activate_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/versions/{n}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/projects/{id}/versions/{n}/comments — tous les fils de la version (lecture seule). */
        get: operations["list_comments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/versions/{n}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/projects/{id}/versions/{n}/preview — sert le HTML brut de la version. */
        get: operations["preview_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/public/{slug} — meta publique pour la page de déverrouillage.
         *     Renvoie `brand_name` + `code_enabled`, jamais le PIN (DTO sans champ pin).
         */
        get: operations["public_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/settings — infos de branchement du connecteur MCP Claude. */
        get: operations["get_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/c/{slug}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /c/{slug}/comments — mes pins+fils de la version active. */
        get: operations["list_comments"];
        put?: never;
        /** POST /c/{slug}/comments — crée un pin + 1ᵉʳ message ; pose le cookie d'identité si absent. */
        post: operations["create_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/c/{slug}/comments/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** PUT /c/{slug}/comments/messages/{id} — édite mon message. */
        put: operations["edit_comment"];
        post?: never;
        /** DELETE /c/{slug}/comments/messages/{id} — supprime mon message. */
        delete: operations["delete_comment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/c/{slug}/comments/pins/{pin}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** DELETE /c/{slug}/comments/pins/{pin} — supprime mon pin entier. */
        delete: operations["delete_comment_pin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/c/{slug}/comments/pins/{pin}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /c/{slug}/comments/pins/{pin}/replies — ajoute un message à un pin existant. */
        post: operations["reply_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Réponse d'activation : confirme la bascule et renvoie le pointeur actif. */
        ActivateResponse: {
            /** Format: int32 */
            active_version_id: number;
            ok: boolean;
        };
        /** @description Réponse de `GET /api/projects/{id}/versions/{n}/comments`. */
        AdminCommentList: {
            pins: components["schemas"]["AdminCommentPin"][];
            /** Format: int32 */
            version: number;
        };
        /** @description Message vu par l'admin (lecture seule — pas d'`editable`, jamais d'`owner_token`). */
        AdminCommentMessage: {
            author_name: string;
            body: string;
            created_at: string;
            /** Format: int32 */
            id: number;
            updated_at: string;
        };
        AdminCommentPin: {
            anchor: string;
            created_at: string;
            /** Format: int32 */
            id: number;
            messages: components["schemas"]["AdminCommentMessage"][];
        };
        /** @description Réponse de `GET /c/{slug}/comments`. */
        CommentList: {
            pins: components["schemas"]["CommentPin"][];
            /** Format: int32 */
            version: number;
        };
        /** @description Message d'un fil, vu par le visiteur (jamais d'`owner_token`). */
        CommentMessage: {
            author_name: string;
            body: string;
            created_at: string;
            /** @description `true` si l'appelant courant est l'auteur (peut éditer/supprimer). */
            editable: boolean;
            /** Format: int32 */
            id: number;
            updated_at: string;
        };
        /** @description Pin + son fil, vu par le visiteur. */
        CommentPin: {
            anchor: string;
            created_at: string;
            /** Format: int32 */
            id: number;
            messages: components["schemas"]["CommentMessage"][];
        };
        /** @description Corps de `POST /c/{slug}/comments` — crée un pin + 1ᵉʳ message. */
        CreatePinReq: {
            /** @description Descripteur d'ancrage JSON opaque (le serveur ne l'interprète jamais). */
            anchor: string;
            author_name: string;
            body: string;
        };
        CreateProjectReq: {
            brand_name?: string | null;
            code_enabled?: boolean;
            comments_enabled?: boolean | null;
            name: string;
            pin?: string | null;
        };
        DeployReq: {
            activate?: boolean;
            html: string;
            notes?: string | null;
        };
        /** @description Réponse de déploiement : identifiant et numéro de la version créée. */
        DeployResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            n: number;
        };
        /** @description Corps de `PUT /c/{slug}/comments/messages/{id}`. */
        EditMessageReq: {
            body: string;
        };
        LoginReq: {
            pass: string;
            user: string;
        };
        /** @description Réponse générique « succès » (`{"ok": true}`). */
        OkResponse: {
            ok: boolean;
        };
        /** @description Détail — expose le PIN (copiable en admin uniquement, invariant §9.2). */
        ProjectDetail: {
            /** Format: int32 */
            active_version_id?: number | null;
            brand_name?: string | null;
            code_enabled: boolean;
            comments_enabled: boolean;
            /** Format: int32 */
            id: number;
            name: string;
            pin?: string | null;
            slug: string;
            versions: components["schemas"]["VersionItem"][];
        };
        /** @description Item de liste — **sans PIN** (invariant §9.2 : structurellement absent). */
        ProjectListItem: {
            /**
             * Format: int32
             * @description Numéro (`n`) de la version active, ou `None` si aucun déploiement.
             *     On n'expose PAS `active_version_id` (PK interne trompeuse) dans la liste.
             */
            active_version_n?: number | null;
            brand_name?: string | null;
            code_enabled: boolean;
            comments_enabled: boolean;
            /** Format: int32 */
            id: number;
            name: string;
            slug: string;
            /**
             * Format: int32
             * @description Nombre total de versions du projet.
             */
            version_count: number;
        };
        /**
         * @description Meta publique servie à la page de déverrouillage (`GET /api/public/{slug}`).
         *     **Sans PIN** (invariant §9.2 : structurellement absent) — `brand_name` est fait
         *     pour être affiché publiquement sur la page de code.
         */
        PublicMeta: {
            brand_name?: string | null;
            code_enabled: boolean;
            comments_enabled: boolean;
        };
        /** @description Corps de `POST /c/{slug}/comments/pins/{pin}/replies`. */
        ReplyReq: {
            author_name: string;
            body: string;
        };
        SetCodeReq: {
            pin: string;
        };
        /**
         * @description Réponse de `GET /api/settings` — infos de branchement MCP pour l'admin.
         *     Expose `deploy_token` (secret applicatif) à un admin AUTHENTIFIÉ uniquement
         *     (même logique que le PIN au détail). Jamais via MCP, jamais en liste de projets.
         */
        SettingsResponse: {
            deploy_token: string;
            mcp_url: string;
            public_base_url: string;
        };
        UpdateProjectReq: {
            /**
             * @description `Option<Option<String>>` : absent ⇒ inchangé ; `null` ⇒ effacer ; valeur ⇒ définir.
             *     Vu par OpenAPI comme une string nullable (`value_type` force le schéma).
             */
            brand_name?: string | null;
            comments_enabled?: boolean | null;
            name?: string | null;
        };
        VersionItem: {
            /** Format: int32 */
            comment_count: number;
            created_at: string;
            /** Format: int32 */
            id: number;
            is_active: boolean;
            /** Format: int32 */
            n: number;
            release_notes?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginReq"];
            };
        };
        responses: {
            /** @description Authentifié (cookie de session posé) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Identifiants invalides */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session détruite */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des projets (sans PIN) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListItem"][];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectReq"];
            };
        };
        responses: {
            /** @description Projet créé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Requête invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Détail du projet (avec PIN) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Projet inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectReq"];
            };
        };
        responses: {
            /** @description Projet mis à jour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Requête invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Projet inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projet supprimé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Projet inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_code: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCodeReq"];
            };
        };
        responses: {
            /** @description Code activé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clear_code: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Code désactivé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    moderate_delete_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
                /** @description Identifiant du message */
                cid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message supprimé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Message hors projet ou inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deploy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployReq"];
            };
        };
        responses: {
            /** @description Version déployée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
                /** @description Numéro de version */
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version supprimée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Version active : suppression refusée */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Version inconnue */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    activate_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
                /** @description Numéro de version */
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version activée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivateResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Version inconnue */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_comments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
                /** @description Numéro de version */
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commentaires de la version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCommentList"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Version inconnue */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
                /** @description Numéro de version */
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML brut de la version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Version inconnue */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    public_meta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug public du projet */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Meta publique (sans PIN) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicMeta"];
                };
            };
            /** @description Slug inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Infos MCP (deploy_token + URLs) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_comments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug public du projet */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des commentaires du visiteur */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentList"];
                };
            };
            /** @description Projet verrouillé */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Projet inconnu ou commentaires désactivés */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug public du projet */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePinReq"];
            };
        };
        responses: {
            /** @description Pin créé avec son premier message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentPin"];
                };
            };
            /** @description Projet verrouillé ou header manquant */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Projet inconnu ou commentaires désactivés */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    edit_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug public du projet */
                slug: string;
                /** @description Identifiant du message */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditMessageReq"];
            };
        };
        responses: {
            /** @description Message modifié */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentMessage"];
                };
            };
            /** @description Projet verrouillé ou header manquant */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Message inconnu ou étranger */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug public du projet */
                slug: string;
                /** @description Identifiant du message */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message supprimé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Projet verrouillé ou header manquant */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Message inconnu ou étranger */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_comment_pin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug public du projet */
                slug: string;
                /** @description Identifiant du pin */
                pin: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pin supprimé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Projet verrouillé ou header manquant */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pin inconnu ou étranger */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reply_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug public du projet */
                slug: string;
                /** @description Identifiant du pin */
                pin: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyReq"];
            };
        };
        responses: {
            /** @description Message ajouté */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentMessage"];
                };
            };
            /** @description Projet verrouillé ou header manquant */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pin inconnu ou étranger */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
