/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/login — vérifie ADMIN_USER/ADMIN_PASS à temps constant, pose la session. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/logout — invalide la session côté serveur (supprime la ligne en DB). */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/projects — liste tous les projets (sans PIN, invariant §9.2). */
        get: operations["list"];
        put?: never;
        /** POST /api/projects — crée un nouveau projet. */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/projects/{id} — détail d'un projet avec ses versions et son PIN. */
        get: operations["detail"];
        /** PUT /api/projects/{id} — met à jour le nom ou le brand_name d'un projet. */
        put: operations["update"];
        post?: never;
        /** DELETE /api/projects/{id} — supprime un projet et ses versions. */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/projects/{id}/code — active le code d'accès avec le PIN fourni. */
        post: operations["set_code"];
        /** DELETE /api/projects/{id}/code — désactive le code d'accès (PIN effacé). */
        delete: operations["clear_code"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/projects/{id}/deploy — déploie un nouveau HTML, crée une version. */
        post: operations["deploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/versions/{n}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** DELETE /api/projects/{id}/versions/{n} — supprime une version NON active. */
        delete: operations["delete_version"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/versions/{n}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/projects/{id}/versions/{n}/activate — bascule le pointeur actif. */
        post: operations["activate_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/versions/{n}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/projects/{id}/versions/{n}/preview — sert le HTML brut de la version. */
        get: operations["preview_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Réponse d'activation : confirme la bascule et renvoie le pointeur actif. */
        ActivateResponse: {
            /** Format: int32 */
            active_version_id: number;
            ok: boolean;
        };
        CreateProjectReq: {
            brand_name?: string | null;
            code_enabled?: boolean;
            name: string;
            pin?: string | null;
        };
        DeployReq: {
            activate?: boolean;
            html: string;
        };
        /** @description Réponse de déploiement : identifiant et numéro de la version créée. */
        DeployResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            n: number;
        };
        LoginReq: {
            pass: string;
            user: string;
        };
        /** @description Réponse générique « succès » (`{"ok": true}`). */
        OkResponse: {
            ok: boolean;
        };
        /** @description Détail — expose le PIN (copiable en admin uniquement, invariant §9.2). */
        ProjectDetail: {
            /** Format: int32 */
            active_version_id?: number | null;
            brand_name?: string | null;
            code_enabled: boolean;
            /** Format: int32 */
            id: number;
            name: string;
            pin?: string | null;
            slug: string;
            versions: components["schemas"]["VersionItem"][];
        };
        /** @description Item de liste — **sans PIN** (invariant §9.2 : structurellement absent). */
        ProjectListItem: {
            /**
             * Format: int32
             * @description Numéro (`n`) de la version active, ou `None` si aucun déploiement.
             *     On n'expose PAS `active_version_id` (PK interne trompeuse) dans la liste.
             */
            active_version_n?: number | null;
            brand_name?: string | null;
            code_enabled: boolean;
            /** Format: int32 */
            id: number;
            name: string;
            slug: string;
            /**
             * Format: int32
             * @description Nombre total de versions du projet.
             */
            version_count: number;
        };
        SetCodeReq: {
            pin: string;
        };
        UpdateProjectReq: {
            /**
             * @description `Option<Option<String>>` : absent ⇒ inchangé ; `null` ⇒ effacer ; valeur ⇒ définir.
             *     Vu par OpenAPI comme une string nullable (`value_type` force le schéma).
             */
            brand_name?: string | null;
            name?: string | null;
        };
        VersionItem: {
            created_at: string;
            /** Format: int32 */
            id: number;
            is_active: boolean;
            /** Format: int32 */
            n: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginReq"];
            };
        };
        responses: {
            /** @description Authentifié (cookie de session posé) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Identifiants invalides */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session détruite */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des projets (sans PIN) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListItem"][];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectReq"];
            };
        };
        responses: {
            /** @description Projet créé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Requête invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Détail du projet (avec PIN) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Projet inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectReq"];
            };
        };
        responses: {
            /** @description Projet mis à jour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Requête invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Projet inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projet supprimé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Projet inconnu */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_code: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCodeReq"];
            };
        };
        responses: {
            /** @description Code activé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clear_code: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Code désactivé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deploy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployReq"];
            };
        };
        responses: {
            /** @description Version déployée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
                /** @description Numéro de version */
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version supprimée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Version active : suppression refusée */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Version inconnue */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    activate_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
                /** @description Numéro de version */
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version activée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivateResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Origin invalide (CSRF) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Version inconnue */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preview_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifiant du projet */
                id: number;
                /** @description Numéro de version */
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML brut de la version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Version inconnue */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
