//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "comments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pin_id: i32,
    pub owner_token: String,
    pub author_name: String,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::comment_pins::Entity",
        from = "Column::PinId",
        to = "super::comment_pins::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CommentPins,
}

impl Related<super::comment_pins::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommentPins.def()
    }
}
