//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::comment_pins::Entity as CommentPins;
pub use super::comments::Entity as Comments;
pub use super::projects::Entity as Projects;
pub use super::versions::Entity as Versions;
